### ISSUE TITLE
"vanishing point" of a line

### ISSUE THREAD

**Issue by liuyao12** [enkimute/ganja.js#10]
Coming from observable, particularly from having seen your Introduction to PGA. (Amazing work, by the way! I'm new to all this, and hope to get a better grip to make things on my own.) One issue with the graphics that looks weird to me is that the line sweeping by should "vanish at the horizon". I haven't tested it out or digged into the code, but I'm guessing you just draw an (infinite) line on the canvas without considering the perspective.

(If you do make the change, you might want to have the line "fade off", instead of abruptly ending at the horizon. I'm only imagining all this, not having seen any actual implementation myself.)

**Comment by enkimute** [comment]
You are absolutely correct - the current visualizer (which is only a handful of lines of code) - simplifies a bit to far when rendering 3D PGA lines on as 2D SVG. I'm currently working on a webGL based visualizer that would not have those problems (and enable 3D CGA visualizations).

It does look really funky when the lines move through that spot ;)

**Comment by saivan** [comment]
Yea, I had to just drop by and write a line here. The work you're doing here is absolutely amazing. I hadn't even heard about most of this stuff before the library. I had no idea you could do projective geometry this way. Honestly really appreciate it!

**Comment by enkimute** [comment]
A new webGL visualizer is available now (gl option on the graph function).
