### ISSUE TITLE
Ace Code Editor Unicode bug

### ISSUE THREAD

**Issue by kungfooman** [enkimute/ganja.js#100]
```js
Algebra(0, 1, ()=> {
    var 𝑖 = 1e1;
    var ℼ = Math.PI;
    var ℇ = Math.E;
    return ℇ ** (𝑖 * ℼ);
})
```

The cursor position will not align with the actual chars anymore:

![image](https://user-images.githubusercontent.com/5236548/102764595-af899580-437b-11eb-82d1-31c2e42e2e4a.png)

**Comment by kungfooman** [comment]
https://github.com/enkimute/ganja.js/commit/6ac9d0b8140c0b7357abff5e44c930736e97e0f8 fixes the selection, but creates a strange imaginary space in front of imaginary `𝑖`:

![image](https://user-images.githubusercontent.com/5236548/102765325-c1b80380-437c-11eb-9e17-57956904309d.png)

But this is just a visual artifact and does not mess up the cursor position (which messed up the ability to properly edit code)

**Comment by enkimute** [comment]
closing this. Works, will occasionally update ACE to see if the visual issue resolves.
