### ISSUE TITLE
3DCGA examples

### ISSUE THREAD

**Issue by hugohadfield** [enkimute/ganja.js#11]
Hi @enkimute I am currrently playing around with different javascript GA libraries as I am keen to write a javascript only replacement for my GAOnline project
gaonline.azurewebsites.net
https://github.com/hugohadfield/GAonline
I really like the look of your project but can't seem to find any examples of 3d plotting with 3dcga, any chance you could point me in the right direction?

**Comment by enkimute** [comment]
The current SVG based visualizer lacked the beef needed for 3D CGA - I'm working on a webGL visualizer to address that issue. (of course algebra wise - much of what you would need is already built-in - including matrix-free inverses, fast regressive product, and more)

**Comment by enkimute** [comment]
Here's a quick try at a previewer using the new gl visualizer. It doesn't do native conformal space yet but as the notebook shows, you can easily use two Algebra's (one conformal, one projective) to get around that.

[ObservableHQ Conformal Space Visualisation notebook](https://beta.observablehq.com/@enkimute/3d-conformal-space)

**Comment by hugohadfield** [comment]
First off all, wow, that notebook looks really cool! I have had to stall a bit on working on visualisation as I have to do some writing up of my work this year. Really really keen to work on this with you though! For me when I started with GAOnline I was really interested in building a simple visualiser as fast as I could and I already had a lot of the code to extract the traditional parameterisations (eg. centre, radius, direction...) of geometric primitives from CGA41 objects (mostly using algorithms/formulae from the Lasenbys' [Covariant Approach to Geometry](http://www2.montgomerycollege.edu/departments/planet/planet/Numerical_Relativity/GA-SIG/Conformal%20Geometry%20Papers/Cambridge/Covarient%20Approach%20to%20Geometry%20Using%20Geometric%20Algebra.pdf)). I had previously worked with threejs so it seemed like a pretty easy project to just shove them all together and see what happened!

**Comment by hugohadfield** [comment]
Speaking to people at the AGACSE conference it seemed people were interested in being able to visualise general distance functions and in particular [Vincent](http://igm.univ-mlv.fr/~vnozick/?lang=en) and I were discussing trying to get some masters students together in France to work on in browser rendering of cga and other algebras. We were also potentially discussing trying to compile his c++ library garamon to web assembly as it pretty speedy. Mostly though I think it would be a huge boon for the field to be able to create an inbrowser replacement for GAViewer with an interface language that is high level and well known eg. javascript or python

**Comment by enkimute** [comment]
Hi hugo,

The conformal visualiser (based on that notebook) should land in ganja.js in the next few days. Once it does I'll be sure to shoot Vincent an email. I'm also playing around with an implementation that directly renders CGA objects using raytracing on the distancefields for these objects. (have some slow albeit promising 2D CGA samples running already).

I'll keep you posted.

Cheers,

Steven.

**Comment by hugohadfield** [comment]
Sounds great!

**Comment by enkimute** [comment]
[new 3D CGA example added to the coffeeshop and preliminary conformal visualizer released.](https://enkimute.github.io/ganja.js/examples/coffeeshop.html#cga3d_points_and_spheres)

I'm guessing this issue can now be closed - I'll add more examples once I find some time.

Cheers.

**Comment by citron** [comment]
Thanks a lot ! already 3 very good  examples to play with 3D CGA !
Two questions about 3D CGA: 
What is the most elegant way to draw a **great circle** passing through two points ?
A great circle contains two arcs, a small one, a big one. How can I paint things like that ?
![Arcs and Great Circle](https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Illustration_of_great-circle_distance.svg/330px-Illustration_of_great-circle_distance.svg.png)

**Comment by enkimute** [comment]
Hi Citron,

Thanks, the update is still being worked on - I'll re-open this issue and will try to answer your questions :

Constructing the great circle through two points in CGA can be done very eloquently. Using the following two observations :

* Any circle is uniquely defined by three points.
* great circles are the only circles on a sphere that for any (and all points) **p** also contain the antipodal point **p' = center-p**

Knowing that, and given two points **a** and **b**, we see that there are two possibilities 

* **a** and **b** are not each other's antipodal.  (**a+b <> center**) The great circle through them can be constructed as **a**^**b**^**a'** or **a**^**b**^**b'** (where **a'** and **b'** are the antipodals of **a** and **b**)

* **a** and **b** are each others antipodal. (**a+b=center**) In this case there are infinitly many great circles through **a** and **b** and they can be found by randomly picking any other point on the sphere **c**. The great circle is then found as **a**^**b**^**c**

Rendering just the **great arcs** is a task similar to rendering **line-segments** in PGA, and we would simply parametrize the arc (as a rotation starting from point **a** in the plane of the great circle - which itself is found by wedging the great circle with infinity).

I however still have to add segment- and polygon-rendering to the conformal visualizer. When I do I'll either add a coffeeshop sample or create an observable notebook to demonstrate this.

Cheers 👍

**Comment by citron** [comment]
Thanks for the explanation !
I'll wait for the "segment" rendering solution. Would be happy to contribute but I do not have your coding and math knowledge.

**Comment by enkimute** [comment]
Progress on the conformal visualizer can be followed in a new notebook :

[observableHQ : Conformal Geometric Algebra](https://beta.observablehq.com/@enkimute/conformal-geometric-algebra)

**Comment by enkimute** [comment]
Citron,

That notebook has been updated, last example now demonstrates calculating and rendering great circles and arcs through any two given points ;) 

(https://beta.observablehq.com/@enkimute/conformal-geometric-algebra)

Cheers.

**Comment by enkimute** [comment]
I'm assuming this issue can be closed ? Feel free to bother me for other examples !

**Comment by hugohadfield** [comment]
Yes thanks @enkimute I'll close this now but will drop you an email as it would be great to chat about what your plans are with the library for the future etc!
