### ISSUE TITLE
TypeError: t is undefined

### ISSUE THREAD

**Issue by hugohadfield** [enkimute/ganja.js#12]
While attempting to play around with 3dcga I get a strange type error buried deep in ganga which I am struggling to debug:

TypeError: t is undefined[Learn More]
translate
file:///home/hugo/phd/ganja.js/ganja.js:422:196
translate
file:///home/hugo/phd/ganja.js/ganja.js:427:203
inline
file:///home/hugo/phd/ganja.js/ganja.js:479:100
Algebra
file:///home/hugo/phd/ganja.js/ganja.js:521:40
<anonymous>
file:///home/hugo/phd/ganja.js/examples/cga3d.html:16:14

Here is my script:
https://gist.github.com/hugohadfield/ad14fdf02bcf22e2e3eec897a405bb2e
any help with this would be immensely appreciated as the stack trace I get is very hard to decipher for a javascript newbie like myself!

**Comment by enkimute** [comment]
Hi Hugo,

You´ve stumbled upon a parse bug - I'll look into this tomorrow - In the mean time you can work around it by changing the '-' on line 28 to '-1*' .. although there's more things that will need fixing (missing var keywords etc ..)

It may be interesting to compare notes and ideas as I'm working on a webGL based visualizer for PGA and CGA myself. (ganja.js currently uses SVG which worked up to 2D CGA but for 3D CGA it's to cumbersome).

**Comment by enkimute** [comment]
Btw, for an updated version of your gist, see my fork.

https://gist.github.com/enkimute/c462fc7e33e70869f5262cbd6a153958

**Comment by hugohadfield** [comment]
Amazing, thanks for the help Steven!
