### ISSUE TITLE
Length Metric Problem at Observable.

### ISSUE THREAD

**Issue by jahbini** [enkimute/ganja.js#131]
My notebook has problems: https://observablehq.com/@jahbini/3d-pga-length-quandry

The Length of "seemingly equal" line segments is way off as documented at that notebook.

Clearly, I have shot myself in the foot... Somehow.

Any assistance?

**Comment by enkimute** [comment]
When using a line to measure the distance between two points, first make sure both points are normalized.

https://observablehq.com/d/3cf610cadae3e02e

btw, you may also like:

https://enkimute.github.io/ganja.js/examples/coffeeshop.html#EOzkYY3hj

Cheers,

**Comment by jahbini** [comment]
Thanks!  Straight forward explanation.  Q: do 'all' derived points need normalizing before they behave nicely in the system? Or is Length the only problem?  So much to learn.

As for https://enkimute.github.io/ganja.js/examples/coffeeshop.html#EOzkYY3hj --
It is the Pristine Chapel of Sacred Geometry.  And you can tell 'em I Said So.

**Comment by enkimute** [comment]
Well the metric relations often assume normalized elements. (distances and angles) - For incidence (lies on, intersections, ..) it makes no difference. In practice I normalize only when I'm doing explicit metric calculations.

For some applications it may be useful to represent mass or energy using that homogeneous scale - it works out nicely when using e.g. PGA lines to represent forces or momentum lines.

Cheers,

S.

**Comment by skydog23** [comment]
Might it make sense to introduce two versions of the metric formulas, one
for normalized arguments (it seems the current versions behave this way)
and a second more general version that normalizes all arguments? Developers
could use the general form for prototyping and then specialize to the
normalized-argument form after they get things working and care about speed.

**Comment by jahbini** [comment]
Is there a reason that metric operations (distances and angles) should NOT always coerce their arguments into normalized entities?

Contrarywise, would it be reasonable to add a boolean attribute `normalized` that can be set on an `Element`to indicate that metric operations can check before automatically normalizing?

Either way, the opportunity for errors like mine might go away, making me look better in the eyes of my boss.
