### ISSUE TITLE
ganja.js:404 Uncaught TypeError: Cannot read property 'enable' of null

### ISSUE THREAD

**Issue by citron** [enkimute/ganja.js#14]
The WebGL CGA code leads to an error on IOS and MacOS, chrome or Safari.
12ganja.js:404 Uncaught TypeError: Cannot read property 'enable' of null

It hangs at the gl.enable(...) call, line 404 of the last ganja.js code.

**Comment by enkimute** [comment]
Hi Citron - this is probably the lack of support for webGL2, I'll see if I can convert things back to webGL1, in the mean time I'll add some error handling to properly report on the situation.

Thanks for the heads up !

**Comment by enkimute** [comment]
I "upgraded" the GL visualizer from webGL2 to webGL1 ;) .. it should now work fine on IOS and macOS.
