### ISSUE TITLE
"viewof" variables in ganja inline functions 

### ISSUE THREAD

**Issue by citron** [enkimute/ganja.js#15]
This is nor a bug nor a pure ganja.js issue but, in an _observable_ notebook, how do we get access to a "_viewof_" declared variable in a " `CGA.inline((f)=>{ ... })(f)` " construction ?

**Comment by citron** [comment]
So Great ! Waiting for it in CGA !
Thanks !

**Comment by enkimute** [comment]
Working on it [here](https://beta.observablehq.com/@enkimute/conformal-geometric-algebra) - working but looks like its a frame behind .. tbc

**Comment by enkimute** [comment]
basic interactivity and viewof response added .. the last demo in [this notebook](https://beta.observablehq.com/@enkimute/conformal-geometric-algebra). Demonstrates the use of viewof to render great arcs in CGA, where the user can drag the two points around and get feedback both on the graph and in other observable cells.

I assume this issue can be closed ?

**Comment by citron** [comment]
Awesome !
now that we can drag the points, it works better than what I requested.
By the way, now the "Segments and Triangles" section poses me two problems :
1/ The figures are not redrawn when you move a point
2/ we are allowed to drag "no" - which is defined as .5e5-.5e4 - but I would suggest to make it immutable (  because if you can alter "no" then why not alter "ni" ? it would lead us to an "Ekke Ekke Ekke Ekke Ptang Zoo Boing!" basis. ). Immutable.js could help.

And yes, this issue can be closed. Thank you very much.

**Comment by enkimute** [comment]
Hehe - excellent ! 

you can easily make it immutable for the graphs by adding a "()=>" where its graphed .. that way you can pick between both behaviors :) - I'll update the other samples on that page so they respond as expected :)

👍

**Comment by enkimute** [comment]
They should all work as expected now.  (only very minor changes .. an extra functional here and there.) - next up are better camera controls for the GL visualizer. (better as in .. any ..)
