### ISSUE TITLE
Feature Request : more than 10 dimensions

### ISSUE THREAD

**Issue by enkimute** [enkimute/ganja.js#17]
Higher dimensional algebras. (Support for an alternate sparse format may need to be considered).
(request by @darkshikamo / Vincent Nozick)

**Comment by darkshikamo** [comment]
> after running some tests on a locally modified version, it is clear that a sparse format will be an absolute requirement for these types of spaces.
> 
> Generating a 10 dimensional Algebra with the current strategy took 18 seconds. A fifteen dimensional one ran out of memory (on my 32 gig machine).
> 
> In general for these types of spaces explicit construction of Cayley-tables is not an option. An alternate implementation of the Generator is required. As I'm keen on trying the QCGA setup I may give this a try soon.

An option is to use a recursive apporach that actually has a better complexity than standard methods. More info here: http://www-igm.univ-mlv.fr/~vnozick/geometricAlgebra.php

**Comment by enkimute** [comment]
already on it !

For low dimensional spaces I suspect it wont help ganja.js speed much - ganja.js only used the tables to generate optimized script code. (which is then subsequently JIT compiled)

btw .. @hugohadfield .. reviewing the python code you referenced, there's a trick from my 80's hat that at first sight could enable some extra performance there .. its a loop-free bitcount :

```c
// v = input value, c = output bitcount.
v = v - ((v >> 1) & 0x55555555);
v = (v & 0x33333333) + ((v >> 2) & 0x33333333);  
c = ((v + (v >> 4) & 0xF0F0F0F) * 0x1010101) >> 24; 
```

**Comment by enkimute** [comment]
For those following, an initial per-grade-storage prototype that can handle 9,6 space easily can be found in [this notebook](https://beta.observablehq.com/d/cd315f194cefe2bd). It is very unoptimized, but even so results are encouraging. (about 5 times slower than 4,1 CGA for vector/bivector geometric product).

I'm currently making the changes on ganja to support multiple generators - and specifically also multiple storage models. i.e. big update coming up ..

**Comment by enkimute** [comment]
The new graded algebra (initial) version has (**finally**) made it into the ganja.js release - currently support for geometric, outer, left contraction and regressive product. Duals supported for all metrics. There's a minimal example [here in the coffeeshop.](https://enkimute.github.io/ganja.js/examples/coffeeshop.html#qcga3d_points_and_more). For practical use - optimizations and a good OPNS visualizer are up next.

I'll keep this open for a bit longer for further suggestions/comments.  (@darkshikamo / @hugohadfield )
