### ISSUE TITLE
Feature Request : Orbit camera controls

### ISSUE THREAD

**Issue by hugohadfield** [enkimute/ganja.js#20]
Would be great to be able to change the viewpoint interactively

**Comment by enkimute** [comment]
on it .. please hold.

**Comment by enkimute** [comment]
(just heading and zoom (wheel) in conformal gl viz for now ..)

**Comment by hugohadfield** [comment]
This is super nice thanks @enkimute :+1:

**Comment by citron** [comment]
hello !
The issue was closed but I do not see how to activate and orbit camera, as the one found [here](https://developer.playcanvas.com/en/tutorials/orbit-camera/) for instance.
In CGA3D, East-West is OK but no North-South movement.
Did I miss something ?

**Comment by citron** [comment]
Perfect ! I'll wait for the IPNS/OPNS visualizer. Thanks !

**Comment by citron** [comment]
Never too late !
Thanks !
