### ISSUE TITLE
Feature Request: Rendering lists of anonymous fucntions

### ISSUE THREAD

**Issue by hugohadfield** [enkimute/ganja.js#21]
See:
https://beta.observablehq.com/@hugohadfield/conformal-geometric-algebra

Essentially this is about rendering lists of objects without specific names that update dynamically as you move points about... might be a bit of a nasty one... Any alternate api type thing that achieves the same goal would be great!

**Comment by enkimute** [comment]
Instead of doing

```javascript
this.graph(array)
```
you can also do :
```javascript
this.graph(function(){
  dynamic_array = []; // then add stuff to it.
  return dynamic_array;
});
```
On the road, when I get home I'll fork that to give you an example. Typically when you go this way for graphing, you can do all your dynamic calculations inside that function and just leave the control points on the outside scope.

**Comment by enkimute** [comment]
[Here you go .. at least I think this is what you wanted ?](https://beta.observablehq.com/d/5759ae7daa2014db)

**Comment by hugohadfield** [comment]
Perfect that is exactly what I was after!
