### ISSUE TITLE
Ability to load and save local files for rendering

### ISSUE THREAD

**Issue by hugohadfield** [enkimute/ganja.js#23]
The ability to upload local files of multivectors into the coffeeshop, ideally of the form discussed in https://github.com/pygae/clifford/issues/61, and, additionally to be able to save the same files, would be fantastic and would aid with easy embedding of ganja into desktop apps and offline sharing of visualisations.

**Comment by enkimute** [comment]
The coffeeshop now has a 'copy to clipboard' option in the 'inspect stash' tab - where you can copy your stash. (just paste in notepad for a local save). (I'll add a href that you can 'save-as' soonish).

There is also an example of how to load and display the data in such a json file (which is using the same format as the graph call). The example is [here](https://enkimute.github.io/ganja.js/examples/example_cga3d_json.html) and in the coffeeshop. (it's for CGA but can easily be adjusted for other Algebras).

Also for the visualization you can now append ```&fullscreen``` to your custom stash url to have it load without editor or tools.

I will also take a look at alternate file formats like hdf5.
