### ISSUE TITLE
Feature Request: Add default camera center position (ideally + orientation) to graph options

### ISSUE THREAD

**Issue by hugohadfield** [enkimute/ganja.js#27]
Would allow default settings for displaying scenes and would allow scripting of camera center etc

**Comment by enkimute** [comment]
Usage example (check the graph options and comments)

https://enkimute.github.io/ganja.js/examples/coffeeshop.html#ciIoi-j_I

(line 24 to 29)

**Comment by hugohadfield** [comment]
Really nice, cheers :+1:
