### ISSUE TITLE
galculator request: make x1, x2.. use subscript for numbers

### ISSUE THREAD

**Issue by JobLeonard** [enkimute/ganja.js#3]
I know this is really stupid, but I was wondering why you need dedicated "times one", "times 2", and so on buttons until I realised they were `x`s!

**Comment by enkimute** [comment]
Thanks - fixed - hope it saves someone else that confusion 👍

**Comment by JobLeonard** [comment]
Don't forget the Android version! ;)

**Comment by enkimute** [comment]
Rolled out on google play - don't know how long it will take to update all 7 of us tho ! ;)

**Comment by JobLeonard** [comment]
I'll let you know :p
