### ISSUE TITLE
draw line between point pairs

### ISSUE THREAD

**Issue by arsenovic** [enkimute/ganja.js#31]
would it make sense to allow for point pairs to have  a line connecting them? maybe this would be a good way to draw vectors?

**Comment by enkimute** [comment]
Hi Alex,

Line segments are currently drawn using a javascript/JSON array of two points. For default parametric interpretation I've tried to stay close to the actual OPNS shapes.

Given a bunch of points P<sub>x</sub>, point pairs PP<sub>x</sub>, lines/circles L<sub>x</sub> and spheres/planes S<sub>x</sub> the following gives an overview of the rendering syntax : 

```javascript
Algebra(4,1,()=>{
   ...
   var canvas = this.graph([
      0xFF0000,                                     // use hex to set colors .. this is red.
      Px,                                           // render a point. (1-vector)
      PPx,                                          // render a point pair (2-vector)
      Lx,                                           // render a line/circle (3-vector)
      Sx,                                           // render a sphere/plane (4-vector)
      [Px,Py],                                      // render a line segment from Px to Py
      [Px,Py,Pz],                                   // render a (convex) polygon
      "label",                                      // render text near the last rendered item.
      { data: [Px,Py,Lx,Ly,...] }                   // render an immutable object (fast but non-interactive)
   ],{gl:true,conformal:true});
   ...
})
```
On top of that when working directly in javascript, each item can also be a function that returns any item, and will be re-evaluated when the user drags items around.

I don't know how much of this API has been exposed/wrapped by Hugo.
