### ISSUE TITLE
Dragging issue using width:window.innerWidth option to graph() function

### ISSUE THREAD

**Issue by skydog23** [enkimute/ganja.js#33]
I was just testing out the nifty new SVG attributes and decided to use a wide drawing canvas using the width:window.innerWidth option to the graph() function. However when I then tried to drag points it appears that the conversion between different coordinate systems isn't taking into account this width.  It appears that the input works correctly but it draws the output point as if it were drawing in the smaller default window. When I delete the width:window.innerWidth option (defaulting to a 500 pixel square I think) dragging works like it should. See for example https://beta.observablehq.com/@skydog23/the-polarity-with-respect-to-a-conic, drag the point B.  Then remove the width:window.innerWidth option and drag B: everything fine.

**Comment by enkimute** [comment]
Fix is online here and on npm. (Sorry for the delay ! If the update hasn't landed yet on the cdn, try ```require("ganja.js@latest")``` on observable instead. (which is how I tested)
