### ISSUE TITLE
Feature request: Camera position + rotation querying

### ISSUE THREAD

**Issue by hugohadfield** [enkimute/ganja.js#35]
I'm trying to draw the camera position + rotation + scale and the orbit center in the CGA visualiser but can't work out a nice way of querying the camera... does this functionality exist? If not would it be difficult to create? I had a dig into the javascript but couldn't work out how to access the M matrix!

**Comment by enkimute** [comment]
Hey Hugo, simply store a reference to the options object you pass to the graph function. All the relevant variables are stored in that object. 

```javascript
  var options = { gl : true, conformal : true };
  var canvas = this.graph([...], options);
  // now you can still reference the options object and read
  // camera settings, zoom etc from it. e.g. :
  // options.posx
  // options.posy
  // options.posz
  // options.z   -> zoom. (i.e. posx,posy,posz is focal center .. then it moves 'z' backwards ..)
  // options.h   -> heading around posx,posy,posz
  // options.p   -> pitching around posx,posy,posz
  // when h=0 and p=0, +y is up and +z is into the screen.
  // unless you provide defaults, these numbers will only exist once the user changes them.
```

**Comment by hugohadfield** [comment]
fantastic, thats really nice, thanks Steven
