### ISSUE TITLE
scalars in the regressive product

### ISSUE THREAD

**Issue by chakravala** [enkimute/ganja.js#38]
It seems that there is a bug with the way scalars are handled in the regressive product for dual numbers, in this case `Algebra(0,0,1)` in ganja cheatsheet
```
(1+2e0) & (3+4e0) = 10+8e0
1 & (3+4e0) = 4
1 & 3 = 3
1 & 4e0 = 4
2e0 & (3+4e0) = 6+8e0
2e0 & 3 = 0
2e0 & 4e0 = 8e0
```

**Comment by chakravala** [comment]
Now, I get the following (i think related) issue
```
1<<4e0 = 4e0
2e0<<3 = 0
```
however, previously that was `2e0<<3 = 6e0` and strangely, in `Grassmann` in Julia implementation, I currently have the same issue as you, but reversed I get
```
1<<4e0 = 0
2e0<<3 = 6e0
```
so it seems that changing the regressive product affects the contraction in both our code

**Comment by enkimute** [comment]
How is this an issue ? 

The << is left contraction, supposed to be assymetric ... If you want the symmetric inner product use "|" instead : 
```
1<<4e0 = 4e0;     // the orthogonal complement of the projection of '1' in '4e0' is '4e0'
4e0<<1 =  0;      // zero, cause '4e0' wont fit in '1'
1|4e0 = 4e0;      // inner product (symmetric)
4e0|1 = 4e0;      // inner product (symmetric)
```
I read **a** left contraction **b** as :

the **orthogonal complement** (in the subspace of **b**) of the projection of **a** onto **b** 

if **a** is scalar, the orthogonal complement to 'none of the space' is 'all of the space'
if however **b** is scalar, there's no space to project or complement in.

**Comment by chakravala** [comment]
Thanks for clarifying, I believe an issue would be that ganja cheatsheet seems to confuse `<<` and `|`

**Comment by chakravala** [comment]
It seems that you have chosen the Left Contraction over the Right Contraction, the reason why I chose the Right Contraction is because it is the original one recommended by Grassmann

Why did you end up choosing the Left over the Right contraction? Do you have both?
