### ISSUE TITLE
How to change the x/y extent and center the camera of an X, Y plane

### ISSUE THREAD

**Issue by petulla** [enkimute/ganja.js#39]
Apologies for this basic question. I recently used Ganja [in this notebook](https://observablehq.com/@petulla/explorable-linear-algebra-cheatsheet) and it was great! I tried passing in an object  to control the camera position without any success.

Could you modify this code below so that the camera is centered at the origin and the zoom is higher?

```js
P2`this.graph(()=>{
  var z = ${v1}
  var pm = ${pp.selection.data}

  var p=(x,y)=>1e12-(x-1)*1.8*1e02-(y-1)*1.8*1e01;

  var a=p(0,0), b=p(z[0],z[1])
  var c=p(1.5,1), p=p(pm[0], pm[1])

  return [,(1+.9e01)>>>1e1,"y",(1-.9e02)>>>1e2,"x",
          0x44AA44,[a,b],0,[a,b],a,"0,0",b,"b",
          0x44AA44,[a,c],0,[a,c],a,"0,0",c,"a",
          0x44AA44,[a,p],0,[a,p],a,"0,0",p,"p",
          0xfdb3b3,[b,p]
  ]}, { // adding the object here with xpos,ypos etc did not seem to work. })`;
```

**Comment by enkimute** [comment]
As soon as I get to a computer ..

**Comment by petulla** [comment]
Take your time!!

**Comment by enkimute** [comment]
I've added some features to address your use case better... they're on npm and there's a sample notebook here : 

[https://observablehq.com/d/0558a38bfeff515d](https://observablehq.com/d/0558a38bfeff515d)

btw .. love Strang's book .. and his ocw videos :) 

Cheers,
