### ISSUE TITLE
Naive question on dev: a minimal example with Ace and Ganja?

### ISSUE THREAD

**Issue by ying17zi** [enkimute/ganja.js#42]
Thank you for make such great lib, and congratulate that you obtained the Best Paper Award at ENGAGE 2019.

I'm wondering what's your working environment/workflow?
Do you have a minimal working example with Ace and Ganja enabled?

Thanks,
Hongying

P.S. My clone of your coffeeshop does not update on modification and the GA code does not appear. If I click "new", paste example code there, and click "run", the result rendering part does not update either. (The individual examples render correctly; and the result in web browser updates on modification that occurs in external text editor.)

I'm switching to Ganja for geometric analysis, but have never touched web development.
I figured out that you are using Ace (https://github.com/ajaxorg/ace).
I tried to minimize coffeeshop page and also to tweak examples provided by Ace to obtain a working environment. But progress slowly :(.

**Comment by enkimute** [comment]
Hi Hongying,

Thank you for your nice words, and to consider using ganja.js for your own work. Please do not hesitate to ask for help, new to javascript and web, I understand that things may be a bit confusing. 

The easiest starting point for the coffeeshop is simply using it. It requires no account or login and allows you to create and share your GA experiments easily. (they can be edited on the computer you created them - visit the 'my stash' tab in the left hand pane of the coffeeshop to find the experiments you've saved.)

[coffeeshop served on github - ready to be used !](https://enkimute.github.io/ganja.js/examples/coffeeshop.html)

You can also skip the coffeeshop altogether and simply edit any of the html files in the examples folder .. those can all be surfed to directly. (simply double-click them).

In browserland, console and debugger can be found by pressing shift+ctrl+i .. to debug ganja.js scripts it is often easiest to insert a 'debugger' statement anywhere in your script (which will cause the debugger to stop at that point if you've opened it with shift+ctrl+i first ..)

There's also an option to use ObservableHQ, which you may like for scientific work, and which integrates ganja.js easily. e.g. : [a simple intro notebook to ganja.js here ..](https://observablehq.com/@enkimute/ganja-js-introduction)

Happy to provide more help if needed !

Cheers,

Steven.

**Comment by ying17zi** [comment]
I just found that my code is still there at my stash. I thought I would lost it without working/saving locally. Sweet feature :)
Thanks for your reply! Great tips!

Cheers,
Hongying
