### ISSUE TITLE
Static point mode disables alpha channel on color

### ISSUE THREAD

**Issue by hugohadfield** [enkimute/ganja.js#64]
When using the {data: ...} in the graph the alpha channel appears to be ignored

Example:
https://enkimute.github.io/ganja.js/examples/coffeeshop.html#vR1VaiUqK

**Comment by waldyrious** [comment]
For future reference, the commit that actually fixed this was c76f08b. Commit 1a4bd9a merely added a code comment to make the logic more explicit.
