### ISSUE TITLE
use fabs rather than abs in cpp template

### ISSUE THREAD

**Issue by hugohadfield** [enkimute/ganja.js#66]
Was getting incorrect results when normalizing, changing abs to fabs solved my problems
https://github.com/enkimute/ganja.js/blob/62aefe6b1dd7fbe294d65a9af9dfdbe6fd3fd1a7/codegen/cpp.template.js#L175

**Comment by eric-wieser** [comment]
This doesn't make a huge amount of sense to me

**Comment by hugohadfield** [comment]
Just came up against this again with some generated code, I think actually std::abs is the better replacement, would that make more sense @eric-wieser ?

**Comment by eric-wieser** [comment]
I remember we discussed this, and I don't remember what we concluded

**Comment by enkimute** [comment]
I changed it to std::abs
