### ISSUE TITLE
Format string expressions use non-GA operators

### ISSUE THREAD

**Issue by eric-wieser** [enkimute/ganja.js#69]
Using ``() => `${(no | ni)}` `` as an argument to `graph` gives `0` not `-1`

**Comment by enkimute** [comment]
Ganja doesn't substitute inside template strings. (it predates template strings and as a quick fix I simply process them as ordinary strings). It is on my todo, but will most likely have to wait till I release the big rewrite (read cleanup) - now this has clearly moved past my personal playground :).

The workaround is to use e.g. the method syntax :

`()=>`${no.Dot(ni)}`

or oldschool string concatenation :

`()=>no|ni+""`
