### ISSUE TITLE
Version in package.json not in sync with latest tag

### ISSUE THREAD

**Issue by waldyrious** [enkimute/ganja.js#76]
The latest tag is [named v1.0.166](https://github.com/enkimute/ganja.js/releases/tag/v1.0.166), but the `package.json` still shows `1.0.151`:

https://github.com/enkimute/ganja.js/blob/e0f0d9e43fabf2ec6573963feff984a3056e50b3/package.json#L3

Strangely, the [NPM page for this package](https://www.npmjs.com/package/validator.js) does show the latest version `1.0.166`. I'm not suree what gives.

By the way, it would be nice to have the NPM badge in the README:

`![npm](https://img.shields.io/npm/v/ganja.js)` → ![npm](https://img.shields.io/npm/v/ganja.js)

**Comment by enkimute** [comment]
will cleanup

**Comment by enkimute** [comment]
fixed !
