### ISSUE TITLE
Syntax errors when parsing 'inline functions'

### ISSUE THREAD

**Issue by kelleyvanevert** [enkimute/ganja.js#8]
Hey! The 'inline function' parsing causes some syntax errors, that are notably unsemantic and make debugging a bit weird sometimes. I collected a few below :)

1. Something to do with comments

```javascript
CGA3D.inline(() => {
  return [
    1, // syntax error
    -2,
  ];
})()
```

```javascript
CGA3D.inline(() => {
  return [
    1, // no syntax error
    (-2),
  ];
})()
```

2. Element/array access

```javascript
CGA3D.inline(() => {
  1e5[0]*1e1; // syntax error
})()
```

```javascript
CGA3D.inline(() => {
  (1e5[0])*1e1; // no syntax error
})()
```

3. Variables

```javascript
CGA3D.inline(() => {
  const a = 5;
  a[0]*1e1; // syntax error
})()
```

```javascript
CGA3D.inline(() => {
  const a = 5e0;
  a[0]*1e1; // no error
})()
```

**Comment by enkimute** [comment]
Thanks, perfect time to rewrite the AST translator.

**Comment by kelleyvanevert** [comment]
Oh, and equality is not currently overloaded, which is also a bit weird:

```javascript
Algebra(2).inline(() => {
  console.log(1e1 == 1); // false
})
```

**Comment by enkimute** [comment]
Example 3 is by design, I want to keep scalars at native speed. (you can always add in 0e1 or similar to 'upcast' a constant real number to be a multivector)
