### ISSUE TITLE
Inline functions: scoping, and name

### ISSUE THREAD

**Issue by kelleyvanevert** [enkimute/ganja.js#9]
I really love the "inline functions": instead of a complete DSL, or dealing with a clunky javascript API, you just add operator overloading to otherwise normal javascript code by a clever preprocessing step acting by inflection on the function's defining string. Nice :) This does bring an unintuitive problem though: it breaks lexical scoping:

```javascript
const a = 5;
console.log(CGA3D.inline(() => {
  return a; // nope
})());
```

A way to deal with this, though a bit cumbersome, is:

```javascript
const api = { a: 5 };
console.log(CGA3D.inline((api) => {
  return api.a; // OK
})(api));
```

...but might there be a way to reconcile "inline functions" with lexical scoping?

*Also, but less important, I'm not sure if "inline functions" is the most logical naming for this feature. What is its rationale?*

**Comment by kelleyvanevert** [comment]
Oh, wait, I get it. "Inlining" as in what compilers to with simple functions :)

**Comment by enkimute** [comment]
Hmm .. I've used the same workaround but you've made me wonder what scope eval runs in .. I'll have to play around and see if any of the create function constructs in js may do the trick .. tbc .. 

Another workaround would be to have a specific namespace that is only used to specify scoping but doesn't perform substitution .. i.e.

```javascript
Algebra().namespace(()=>{
  var a;

  Algebra(3,0,1,()=>{
    var c=1+1e1; 
    console.log(a,c); // substituted.
     
  });

  var c=1+1; // not substituted
});
```

Obviously if a precompile step is an option it would be easy to tweak ganja to simply output the processed result as a string which would retain lexical scoping.

I've been playing around with that idea since I want to try the closure compiler and perhaps even prepack to see how it could optimize GA code.

**Comment by enkimute** [comment]
Actually that namespace idea is not to bad .. I may give that a go .. it would basically process the entire scope, only substitute the algebra calls it finds and then finally run the entire thing ..

**Comment by kelleyvanevert** [comment]
The namespace is clever :)

As far as I can see, you really can't beat lexical scoping. For all the inflection and other crazy things you can do with javascript, I don't think there's a way to inject/mess around with the scope a function runs in. (The best I can think of is `with`, but even then you need an object to start with.) The namespace option might best the best shot.

**Comment by enkimute** [comment]
Well .. never say never .. hows about this : 

It's a bit of a hack I'll admit - but - works in the current version ;) 
```javascript
var aaa=3; 

eval(Algebra(2,0,1,()=>(()=>{ 
  console.log(aaa);

}).toString()))();
```

**Comment by kelleyvanevert** [comment]
Yes, well of course that works, but that's hardly an API..

**Comment by kelleyvanevert** [comment]
If you break it down, there's the following to the inline feature:
- It's essentially just string logic, so there's no magic going on there, but:
- using normal javascript code enables code editors to do their static analysis.

**Comment by enkimute** [comment]
yes. easy-peasy. 

it's just string magic - no logic going on there ;)

**Comment by kelleyvanevert** [comment]
Another road to take, would be to go less "it's just code" and more "register a collection of functions in a defined space", say something like:

```javascript
const A = Algebra(4,1);
const scope = A.scope();
scope.ei = scope.def(() => 1e4 + 1e5)();
scope.f = scope.def(() => ei + 5);
```

Not really the original goal you had in mind, but at least it has a clear API and the other advantages are kept.

**Comment by enkimute** [comment]
Hmm ..  that makes it a lot more top heavy tho, the current scope is shared over several calls to inline so you could use *this* :

```javascript
const A = Algebra(4,1);
A.inline(()=>this.ei = 1e4 + 1e5)();
A.inline(()=>this.ei + 5)(); 
```
Also, in your suggestion referencing ei would not be trivial to substitute (I'd have to explicitely forward to global scope in case of undefined .. ) - so it would have to be *scope.ei* in your example to, similar to *this.ei* in mine.

**Comment by kelleyvanevert** [comment]
Not entirely sure what you mean with forwarding to global scope and undefined, but I'd imagine you want to substitute the operators with DSL functions on your string magic, instead of the variables/subexpressions themselves, if that's what you're now doing. I.e. if replace `x + y` with `plus(x, y)` and have `plus` do appropriate lifting etc, instead of with `<replaced>.plus(<replaced>)`. Does that make sense?

Didn't know that the scope was shared though (didn't really think about it actually), so that's nice :)

**Comment by kelleyvanevert** [comment]
Brainfart. Of course, my example would have to read

```javascript
const A = Algebra(4,1);
const scope = A.scope(); // or .namespace()
const ei = scope.ei = scope.def(() => 1e4 + 1e5)();
scope.f = scope.def(() => ei + 5);
```

And that really cuts to the heart of why the "registering things" method is always so ugly. You have to doubly name things all the time.

It seems that for now the shared scope of multiple inlined functions is the way to go.

**Comment by enkimute** [comment]
I'm currently doing exactly that (only translating the operators) - which would not cover your example (since you reference *ei* without explicit scope in your last line, and ganja.js is not touching identifiers - *ei* would be undefined there)

i.e. your example would have to read :

```javascript
const A = Algebra(4,1);
const scope = A.scope("scopename"); // or .namespace()
scope.ei = scope.def(() => 1e4 + 1e5)();
scope.f = scope.def(() => scopename.ei + 5);
```
You wouldn't be able to do it with just *ei* with the current translator.

**Comment by kelleyvanevert** [comment]
Technically speaking, this works, because of the `with` trick:

```javascript
{
  // library implementation
  const magic = str => str.replace('5', '6');
  const scope = {
    def: f => eval(`(() => { with(scope) { return (${magic(f.toString())}); } })()`),
  };
  
  // user api
  scope.ei = scope.def(() => 4+5)();
  scope.f = scope.def(n => ei+10);
  console.log("ei=",scope.ei,"f=",scope.f()); // ei=10, f=20
}
```

But such an api would really only be logical to emulate "normal lexical scope" if the variable `ei` in the definition of `f` would in normal lexical scoping refer to something, which now it doesn't. You'd have to redundantly write

```javascript
  const ei = scope.ei = scope.def(() => 4+5)();
  scope.f = scope.def(n => ei+10);
```

and maybe the api could encourage this way of coding by strictly separating the two namings to something just javascript and something string-logic:

```javascript
  const ei = scope.def("ei", () => 4+5)();
  const f = scope.def("f", n => ei+10);
```

...but you're still stuck with the typical "register things" ugly redundancy of double names.

**Comment by kelleyvanevert** [comment]
The one time I saw this kind of lexical scoping emulated through scope objects and `with` work real nice, was in the setting of html templating for the mvvm library Knockout.js. You'd write the plain html:

```html
<ul data-bind="foreach: platonic_solids">
  <li><strong data-bind="text: name"></strong> (faces: <span data-bind="text: numFaces"></span>)</li>
</ul>
```

to template objects such as `{ platonic_solids: [ { name: 'Tetrahedron', numFaces: 4 }, ... ] }`

But, the difference is that this templating 'DSL' didn't 'mix' with normal javasctipt code, whereas your inline functions do.

You lose lexical scoping if you let the library do the `eval`, and could only replace it with some kind of object-lookup, either throug with kind of `with`-emulation, or just telling the programmer to store variables in `this`.

**Comment by enkimute** [comment]
yes - that pretty much wraps it up. So I'll go for splitting the scope from the translation, with an explicit, optional syntax. Everything stays the way it is but if you run into scoping problems you can wrap your entire context in an ```Algebra.scope(()=>{})``` that moves the translator one level up so to speak.

I'll try to find some time this week to give that a go.

**Comment by enkimute** [comment]
In the latest ganja.js, the inline function has been upgraded so it can also be used as a template string function. This creates an in for the scoping problem as you could now write :

```javascript
var C = Algebra(0,1).inline,    // complex numbers as template string function
      a = 6;                               // variable in outside scope
C`console.log(1e1+${a})`       // complex function using variable from outside scope
```
For now, I'll consider this a workable setup and close this issue.
